### ISSUE TITLE
start up error: indy.error.PoolLedgerTimeout 

### ISSUE THREAD

**Issue by Durai46** [hyperledger/aries-acapy-plugin-toolbox#131]
Can you please help on this below startup issue?
Attaching to demo_tunnel_1, demo_agent_1
agent_1   | Waiting for tunnel...
agent_1   | Waiting for tunnel...
tunnel_1  | Tunnel to agent:3000 running; mangement available on 4040
tunnel_1  | Tunnel URL is: https://chatty-seals-accept-148-173-100-224.loca.lt
tunnel_1  | GET /status 200 126 - 3.085 ms
tunnel_1  | GET /start 200 61 - 0.477 ms
agent_1   | fetched end point [https://chatty-seals-accept-148-173-100-224.loca.lt]
agent_1   | Setting logging level of acapy_plugin_toolbox to 30
agent_1   | 2022-05-30 08:07:51,147 aries_cloudagent.commands.start ERROR Exception during startup:
agent_1   | Traceback (most recent call last):
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 175, in open
agent_1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
agent_1   |     open_pool_ledger.cb)
agent_1   | indy.error.PoolLedgerTimeout
agent_1   | 
agent_1   | The above exception was the direct cause of the following exception:
agent_1   | 
agent_1   | Traceback (most recent call last):
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
agent_1   |     await startup
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
agent_1   |     await conductor.setup()
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 176, in setup
agent_1   |     self.root_profile, self.setup_public_did and self.setup_public_did.did
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 133, in ledger_config
agent_1   |     async with ledger:
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 277, in __aenter__
agent_1   |     await self.pool.context_open()
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 210, in context_open
agent_1   |     await self.open()
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 175, in open
agent_1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
agent_1   |     ) from err_value
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 175, in open
agent_1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
agent_1   |   File "/home/indy/.venv/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
agent_1   |     open_pool_ledger.cb)
agent_1   | aries_cloudagent.ledger.error.LedgerConfigError: Exception opening pool ledger default: Error: Pool timeout
agent_1   |   Caused by: Pool timeout

**Comment by dbluhm** [comment]
This error is indicative of connectivity issues to the ledger. Are you using the default configuration in the demos? Are there any firewall rules that would prevent your computer from connecting to the ledger on ports that are usually in the 9702-9703 range?
