### ISSUE TITLE
Error creating presentation request with predicate

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-acapy-plugin-toolbox#76]
I think ACA-Py changed integer predicate validation to only allow numbers and it seems the toolbox sends a string. Not sure, but that's what I make up of the error

```
aries_cloudagent.messaging.models.base ERROR RequestPres message validation error:
animo-acme-acapy_1   | Traceback (most recent call last):
animo-acme-acapy_1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base.py", line 133, in deserialize
animo-acme-acapy_1   |     return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
animo-acme-acapy_1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.py", line 723, in load
animo-acme-acapy_1   |     data, many=many, partial=partial, unknown=unknown, postprocess=True
animo-acme-acapy_1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.py", line 904, in _do_load
animo-acme-acapy_1   |     raise exc
animo-acme-acapy_1   | marshmallow.exceptions.ValidationError: {'proof_request': {'requested_predicates': defaultdict(<class 'dict'>, {'age': {'value': {'p_value': ['Not a valid integer.']}}})}}
animo-acme-acapy_1   | 2021-07-05 21:17:18,937 aries_cloudagent.core.dispatcher ERROR Message parsing failed: Error deserializing message: RequestPres schema validation failed, sending problem report
```

**Comment by dbluhm** [comment]
I ran into this recently and thought I got a fix merged :thinking: I'll take a look

**Comment by TimoGlastra** [comment]
Ah shoot, maybe I only updated the ACA-Py plugin, not the toolbox. I'll rebuild and get back to you!

**Comment by dbluhm** [comment]
Hey @TimoGlastra, just wanted to follow up on this; was this issue resolved or is there something we should look into here still?
